build:
  image: cblomart/rpi-basebuild
  commands:
    - CC=musl-gcc CCGLAGS="-static" GOOS=linux GOARCH=arm GOARM=5 go build -ldflags '-linkmode external -s -w -extldflags "-static"' -a  github.com/mholt/caddy
    - cp $(which caddy) ./
publish:
  docker:
    username: cblomart
    password: $$DOCKERHUB_PASS
    email: cblomart@gmail.com
    repo: cblomart/rpi-caddy
    insecure: true
    tag:
       - $$BRANCH
       - $$COMMIT
       - latest
